apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: voting-app-replica
  labels:
    name: voting-app-replica
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app     
  replicas: 2
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80