apiVersion: apps/v1

kind: Deployment

metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app

spec:
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
